### ISSUE TITLE
Converting `Glob::is_match` to receive `&self` instead of `&mut self`

### ISSUE THREAD

**Issue by iesahin** [oxc-project/fast-glob#1]
Hey, thanks a lot for updating the crate. I began to use this instead of globset. 

I have a parallel directory walker that checks paths against an ignore list. As it runs with multiple threads, I was using `ignore_rules: Arc<RwLock<IgnoreRules>>` to pass the ignore rules and if a thread finds a new ignore file, it would update with `ignore_rules.write()` and otherwise would just use `ignore_rules.read()`.

Now, with `fast-glob`, as `is_match` requires a mutable self, it requires a `write()` lock to check the paths. This effectively makes all threads waiting for each other to check the ignore rules. 

How much effort is required to let `is_match` to receive a `&self`? If it's doable without much changes. could you guide me about it and I can work on this a bit?

**Comment by shulaoda** [comment]
The `Glob` in the `fast-glob` is designed to handle glob patterns by using `brace expansion`. For instance, if you create a `Glob` instance with `Glob::new("a/b")`, it translates to the pattern `"{a/b}"`. When you add another pattern using `glob.add("b/a")`, the pattern expands to `"{a/b,b/a}"`.

To optimize the matching process, you can convert all matching patterns into a single brace pattern and then use `glob_match_with_brace` to perform the match. This approach consolidates multiple patterns into one, leveraging the efficiency of `brace expansion` for pattern matching.

**Comment by iesahin** [comment]
I added `Clone` derivation to `Pattern` and let `is_match` use a cloned `pattern`. Tests pass. Benches seem to be affected a bit. I can refactor `Pattern` to keep its matching state internally. Let me take a look at it.

**Comment by iesahin** [comment]
> To optimize the matching process, you can convert all matching patterns into a single brace pattern and then use glob_match_normal to perform the match.

When you have millions of paths in a directory hierarchy to check against this pattern, each of the paths must be checked sequentially. If I have `[path_1, ..., path_n]` and want to filter these with `Glob`, I have to go from `glob.is_match(path_1)` to `glob.is_match(path_n)` one by one, because each of the `is_match` requires a `mut &self` and it's not possible to hold a mutable in two different threads.

**Comment by shulaoda** [comment]
> When you have millions of paths in a directory hierarchy to check against this pattern, each of the paths must be checked sequentially. If I have `[path_1, ..., path_n]` and want to filter these with `Glob`, I have to go from `glob.is_match(path_1)` to `glob.is_match(path_n)` one by one, because each of the `is_match` requires a `mut &self` and it's not possible to hold a mutable in two different threads.

You can use `glob_match_with_brace`.

**Comment by Dav1dde** [comment]
@shulaoda I think there might be a wrong 0.3.2 version pushed to `crates.io`, the 0.3.2 version in github contains a function `glob_match`: https://github.com/shulaoda/fast-glob/blob/af9f662534d87e8c24e391675bd575b64ac451bf/src/lib.rs#L179-L195

The pushed version to `crates.io` does not, in the [docs](https://docs.rs/fast-glob/0.3.2/fast_glob/struct.Glob.html) nor in the [code](https://docs.rs/fast-glob/0.3.2/src/fast_glob/lib.rs.html#176).

I assume this is where the confusion is coming from (myself included).

**Comment by shulaoda** [comment]
@iesahin Sorry, I made a mistake, you can use `glob_match_with_brace`.

**Comment by iesahin** [comment]
Hey, thank you. I didn't notice `glob_match_with_brace` doesn't require a `&mut`, so it solved my issue.
